services:
  db:
    image: postgres:14.1-alpine
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "postgres",
          "-U",
          "user"
        ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=bootcamp
      - POSTGRES_PASSWORD=pwd
    ports:
      - '5433:5432'
    volumes:
      - ./api/src/migrations:/docker-entrypoint-initdb.d/
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
